#FROM ubuntu:focal AS build-env
FROM mcr.microsoft.com/dotnet/sdk:6.0.100-preview.3-focal-amd64 AS build-env
WORKDIR /app

COPY . ./

RUN dotnet nuget add source -n dotnet6 https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json
RUN dotnet publish -c Release -o out --self-contained true --runtime linux-x64 --framework net6.0 /p:RuntimeFrameworkVersion=6.0.0-preview.5.21261.8

FROM ubuntu:focal
#FROM mcr.microsoft.com/dotnet/sdk:6.0.100-preview.3-focal-amd64

WORKDIR /app
COPY --from=build-env /app/out .
RUN apt update && apt install htop
ENTRYPOINT ["./GcTesting"]

